# Site settings
title: "Mark Ross - Senior Full-Stack Engineer"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# theme: modern-resume-theme (Use this iF you are hosting your resume yourself)
remote_theme: krazkidd/resume-template # (Use this if you are hosting your resume on GitHub)

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-remote-theme

# Resume settings
resume_avatar: "krazkidd"
resume_name: "Mark Ross"
resume_title: "Senior Full-Stack Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email: ""

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone: ""
#resume_contact_address: ""

resume_header_contact_info: "Arizona, USA"
display_header_contact_info: "true"

resume_header_intro: >
  <p>
    Adaptable software engineer with professional and hobbyist experience across diverse platforms.
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
#resume_section_recognition: true
#resume_section_links: true
#resume_section_associations: true
#resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/krazkidd"
  #resume_twitter_url: ""
  #resume_dribbble_url: ""
  #resume_facebook_url: ""
  resume_linkedin_url: "https://www.linkedin.com/in/markr314/"
  #resume_instagram_url: ""
  resume_website_url: "https://www.xericode.dev/"
  #resume_medium_url: ""
resume_print_social_links: true

# Design settings
resume_theme: default
