# Site settings
title: "Mark Ross - Senior Full-Stack Engineer"
description: ""

# Build settings
markdown: kramdown
# theme: modern-resume-theme (Use this iF you are hosting your resume yourself)
remote_theme: krazkidd/resume-template # (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  # provided by GitHub by default
  # see https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
  # - jekyll-coffeescript
  # - jekyll-default-layout
  # - jekyll-gist
  # - jekyll-github-metadata
  # - jekyll-optional-front-matter
  # - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-titles-from-headings
  # - jekyll-relative-links

  # supported by GitHub
  # see https://pages.github.com/versions/
  #- jekyll-avatar
  #- jekyll-feed
  - jekyll-remote-theme

  # *not* supported by GitHub (requires custom GitHub Action to build/publish)
  #- jekyll-email-protect
  #- jekyll_github_chart
  #- jekyll-mermaid
  #TODO compare to jemoji
  #- jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Resume settings
resume_avatar_url: "https://github.com/krazkidd.png?size=250"
resume_name: "Mark Ross"
resume_title: "Senior Full-Stack Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email: ""

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone: ""
#resume_contact_address: ""

resume_header_contact_info: "Arizona, USA"
display_header_contact_info: "true"

resume_header_intro: >
  <p>
    Adaptable software engineer with professional and hobbyist experience across diverse platforms.
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
#resume_section_recognition: true
#resume_section_links: true
#resume_section_associations: true
#resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/krazkidd"
  #resume_twitter_url: ""
  #resume_dribbble_url: ""
  #resume_facebook_url: ""
  resume_linkedin_url: "https://www.linkedin.com/in/markr314/"
  #resume_instagram_url: ""
  resume_website_url: "https://xericode.dev/"
  #resume_medium_url: ""
resume_print_social_links: true

# Design settings
resume_theme: default
